Add household giving to gifts history chart
givemomentum/stewardship-frontend pull request #2
Opened 2023-02-08 19:18 UTC by kmjennison

2023-02-08 20:36 UTC, torin-givemomentum requested changes

2023-02-08 20:36 UTC, torin-givemomentum commented on src/apps/tasks/rec-donor-gift-chart.vue
> +    if (!donor && donor.gifts) {
I'm confused by this if statement - is it an operator precedence thing? It seems to be checking donor.gifts after we already know donor is falsy.

2023-02-08 20:36 UTC, torin-givemomentum commented on src/apps/tasks/useTaskListStore.ts
> +      const res = await hooks.api.get(`/rec-sets/${taskModifiable.rec_set.pk}/?expand=recs.donor.household,recs.donor.gifts`);
It seems like you're not calling the donor list endpoint you added in the backend PR, is that right?

2023-02-08 21:36 UTC, kmjennison commented on src/apps/tasks/rec-donor-gift-chart.vue
> +    if (!donor && donor.gifts) {
Sorry, this was just an error. Updated. Meant to just make sure the donor has gifts.

2023-02-08 21:45 UTC, kmjennison commented on src/apps/tasks/useTaskListStore.ts
> +      const res = await hooks.api.get(`/rec-sets/${taskModifiable.rec_set.pk}/?expand=recs.donor.household,recs.donor.gifts`);
@torin-givemomentum Right, keeping this API call was the fastest way forward. The useful part of the backend PR is just the serializer changes.

I used the donors endpoint to explore the DRF mixins and figure I'd leave the list functionality in case it's useful later, but LMK if you'd prefer I revert it.

2023-02-09 20:33 UTC, torin-givemomentum approved these changes

2023-02-09 20:33 UTC, merged